# Generated by Django 4.2.3 on 2023-08-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vehicle', '__first__'),
        ('CustomUser', '0002_alter_customuser_is_responsible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FuelCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters', models.PositiveIntegerField(blank=True)),
                ('millage', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bill_photo', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('car', models.ForeignKey(default='NO VEHICLE', on_delete=django.db.models.deletion.SET_DEFAULT, to='Vehicle.Vehicle')),
                ('driver', models.ForeignKey(default='NO DRIVER', on_delete=django.db.models.deletion.SET_DEFAULT, to='CustomUser.driver')),
            ],
        ),
    ]
