# Generated by Django 4.2.3 on 2023-08-15 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Vehicle', '0003_alter_vehicledriverperiod_options'),
        ('Fuel', '0002_fuelcase_charged_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelcase',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuelcase',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Vehicle.vehicle'),
        ),
    ]
