# Generated by Django 4.2.3 on 2023-08-19 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Fuel', '0003_alter_fuelcase_driver_alter_fuelcase_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcase',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuelcase',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
